### PR TITLE
Add smart-home-mode to API

### PR DESCRIPTION
**Pull request by astrandb**
Add get and put of smart-home-mode

### CODE REVIEW

**Comment by astrandb** [comment]
It could be a good time to make a new release. Changes in last PR #16 are needed for the number platform that is in the pipeline.

**Review by pajzo — APPROVED** [review]

**Comment by pajzo** [comment]
I made a release for version 0.3.0

**Comment by astrandb** [comment]
Great! Thanks.

**Comment by pajzo** [comment]
Are you creating a PR in HA to update the dependency, else i can do it :-)

**Comment by astrandb** [comment]
I can do it. Just want to verify that it works as expected first.

**Pull request merged**
