### PR TITLE
Import classes

### PR DESCRIPTION
**Pull request by astrandb**
Import all "global" classes to \_\_init\_\_.py. This simplifies the import statements for modules using this library.

### CODE REVIEW

**Comment by astrandb** [comment]
Realised that I messed up the branches in my fork. This PR might need a rebase after #1 is merged.

**Review by pajzo — APPROVED** [review]

**Review by pajzo — APPROVED** [review]

**Comment by astrandb** [comment]
Thank you @pajzo 
From my point of view it could be time for a new release of this lib. I have no more pending thoughts and it would simplify further development of the integration if the lib is published to pypi.

**Comment by pajzo** [comment]
I will create a new release with version 0.1.0 :-)

**Comment by astrandb** [comment]
Perhaps you have seen that the publish action failed. Please update the version number in setup.cfg and re-run the action.

**Comment by pajzo** [comment]
It's updated now, and published as 0.1.1

**Comment by astrandb** [comment]
Many thanks.

**Pull request merged**
